### ISSUE TITLE
htmlmin linting

### ISSUE THREAD

**Issue by nschloe** [jonschlinkert/gulp-htmlmin#20]
[html-minifier](https://github.com/kangax/html-minifier#options-quick-reference) says it includes linting. When using through gulp, e.g.,
```
var HTMLLint = require('./path/to/htmlminifier.js').HTMLLint;
var lint = new HTMLLint();
var htmlOpts = {
  collapseWhitespace: true,
  removeComments: true,
  lint: lint
};
[...]
.pipe(htmlmin(htmlOpts))
[...]
```
linting doesn't seem to be operational. Any hints here?

**Comment by shinnn** [comment]
Cannot open the link.

**Comment by nschloe** [comment]
@shinnn Fixed.

**Comment by shinnn** [comment]
I'll look into this issue if I have a time. However, I'm not very interested. 

[The plugin guideline](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) says:

> Your plugin should only do **one thing**, and do it well.

And I agree about that.

Though html-minifier supports the linting, it's better to use another plugin for linting, such as [gulp-htmlhint](https://www.npmjs.com/package/gulp-htmlhint).

For example, [coffee-script](http://coffeescript.org/) supports `join` option but [gulp-coffee doesn't](https://github.com/wearefractal/gulp-coffee/issues/14).

**Comment by nschloe** [comment]
I agree, and thank you for the hint to [gulp-htmlhint](https://www.npmjs.com/package/gulp-htmlhint); I'll just use that.
Feel free to reopen if you ever want to get back to it.
