### ISSUE TITLE
Spaces Left in Lodash Template

### ISSUE THREAD

**Issue by michael-jarosik** [jonschlinkert/gulp-htmlmin#21]
I'm using `gulp-htmlmin` to compress Lodash templates prior to precompilation. The minifier seems to be missing spaces that should be removed. This occurs in a few places but isn't entirely consistent.

It typically occurs in a couple places:
- after an HTML tag containing a template delimiter such as `<input type="hidden" value="<%= data.value %>"> <input ...`
- after a text node containing a template delimiter such as `<div><%= data.text %> </div><div> ...`

But in some cases it's also occurring after a tag with no delimiters (look for `_METHOD` below).

Am I missing a setting in my task? (Template task is disabled to study the htmlmin output.)

```
gulp.task('lodash', function() {
  return gulp.src('dev/js/jst/address.jst')
    .pipe(htmlmin({collapseWhitespace: true}))
    // .pipe(template.precompile())
    .pipe(rename('address.js'))
    .pipe(gulp.dest('dist/js'));
});
```

Here's a sampling -- if you need to see more, just let me know. Thanks for your help.

```
<li id="address-<%= data.address_id %>" class="l-addr--data -rel<%= primary %>" style="display: none"><p class="l-addr--address"><span class="-block"><%= data.fname %>&nbsp;<%= data.lname %>&#8203;</span> <span class="-block"><%= data.address1 %>&#8203;</span><% if (data.address2) { %> <span class="-block"><%= data.address2 %>&#8203;</span><% } %> <span class="-block"><span><%= data.city %>,&#32;</span> <span><%= data.state %>&#32;</span> <span><%= data.zip %>&#8203;</span></span><% if (data.phone) { %> <span class="-block"><%= data.phone %></span><% } %></p><div class="-group"><div class="l-addr--button"><form action="/address-book" method="post" novalidate><input type="hidden" name="_METHOD" value="PUT"> <input type="hidden" name="mode" value="edit"> <input type="hidden" ...
```

**Comment by jonschlinkert** [comment]
this plugin just runs html-minifier, sounds like an issue for that lib?

**Comment by shinnn** [comment]
As @jonschlinkert said. Subscribe https://github.com/kangax/html-minifier/issues/217.

**Comment by michael-jarosik** [comment]
Sure I'll post there - thanks for responding
