### ISSUE TITLE
A "typoed" comma in the html freezes the task

### ISSUE THREAD

**Issue by adgoncal** [jonschlinkert/gulp-htmlmin#24]
I had a typo in my html, a comma between attributes of an element, and gulp-htmlmin froze instead of throwing an error.

example:
```
<span class="class1 class2", id="id1"></span>
```

I was using gulp-htmlmin in conjunction with gulp-angular-templatecache and had no idea which of the dozens of html templates was causing the freeze. In fact, I did not even know what task was causing the freeze. If gulp-htmlmin had thrown an error stating that the html is not valid, and perhaps the name of the file where the error occurred, it would have saved me a lot of time.

I think this is a bug report, but otherwise consider it a feature request.

**Comment by shinnn** [comment]
> a comma between attributes of an element

Like this?

```html
<a id="foo", class="bar"></a>
```

I created a small script to reproduce "freeze", but It doesn't freeze.

### Script

```js
'use strict';

var File = require('vinyl');
var gulpHtmlmin = require('./');

gulpHtmlmin()
.on('data', function(file) {
  console.log(file.contents.toString());
})
.end(new File({contents: new Buffer('<a id="foo", class="bar"></a>')}));
```

### Output

```html
<a id="foo" class="bar"></a>
```

@adgoncal Could you show us the smallest HTML that can reproduce the "freeze" issue?

**Comment by shinnn** [comment]
> If gulp-htmlmin had thrown an error stating that the html is not valid, and perhaps the name of the file where the error occurred, it would have saved me a lot of time.

Read the existing discussion about HTML-lint feature. https://github.com/jonschlinkert/gulp-htmlmin/issues/20#issuecomment-76973119
