### ISSUE TITLE
quoteCharacter option not working

### ISSUE THREAD

**Issue by anthony-dandrea** [jonschlinkert/gulp-htmlmin#25]
Trying to use single quotes, but I keep getting double quotes

```
var htmlmin     = require('gulp-htmlmin');

gulp.task('templates', function() {
    var opts = {
        collapseWhitespace: true,
        quoteCharacter: "'"
    }
    return gulp.src('./src/templates/**/*.html')
        .pipe(htmlmin(opts))
        .pipe(gulp.dest('./dist/templates'));
});
```

**Comment by humbertqz** [comment]
Hi @anthony-dandrea  did you find a workaround ?

I have this:  `<input type="hidden" name="" value='{"keyname":"CAPTCHAJAVER","fallback":"true","orgId":"00Do0000000b6Io","ts":""}'>`

In the output the single quotes are replaced for double quotes, this breaks the code.
