### ISSUE TITLE
improperly strips foreign element "/" closing characters by default

### ISSUE THREAD

**Issue by bkimmel** [jonschlinkert/gulp-htmlmin#30]
For foreign elements like SVG, (especially &lt;stop&gt; &lt;polygon&gt;, etc.) "/" characters are required to close the element (see: http://www.w3.org/TR/html5/syntax.html#start-tags #6).  gulp-htmlmin strips them out by default, which results in invalid SVG that is not readable by the User Agent.  Can be worked around by setting keepClosingSlash: true in options, but the default behavior does the "wrong thing" for embedded SVG (and I would assume other foreign elements like MathML as well.)

**Comment by shinnn** [comment]
Issues with the output should be reported on https://github.com/kangax/html-minifier/issues.
