### ISSUE TITLE
can't work when src("src/**/*.html"),has not 'Finished'   "version": "1.3.0",

### ISSUE THREAD

**Issue by brucecham** [jonschlinkert/gulp-htmlmin#34]
![qq 20151217182759](https://cloud.githubusercontent.com/assets/7899194/11867465/1fcda4b4-a4ec-11e5-99ea-59c193ef4f96.png)
![qq 20151217182856](https://cloud.githubusercontent.com/assets/7899194/11867467/22dfd6fe-a4ec-11e5-8ae1-155caee08f65.png)

**Comment by shinnn** [comment]
> can't work when src("src/**/*.html")

Glob related issues go to https://github.com/gulpjs/vinyl-fs/issues.

**Comment by jonschlinkert** [comment]
is this definitely glob related? @brucecham did you do any debugging? are the files coming through at all? or just not finishing?

**Comment by brucecham** [comment]
I was  found some problem, when the file is too large, the internal syntax error

**Comment by jonschlinkert** [comment]
Ok, that sounds like a https://github.com/kangax/html-minifier issue - but it probably is not related to file size. If you're trying to run this on huge html files with a lot of junk in them, you're probably hitting invalid HTML. Try running an HTML linter before you run this and see if that helps
