### ISSUE TITLE
Parse error on Polymer

### ISSUE THREAD

**Issue by motss** [jonschlinkert/gulp-htmlmin#37]
As `gulp-minify-html` is going to be deprecated, it led us here for a better option.

However, such error never encountered when using `gulp-minify-html` and `gulp-htmlmin` kept throwing erros on lines like this 
`<div id="mainContainer" flex?="{{mode !== 'cover'}}" on-scroll="{{scroll}}">`

**Comment by shinnn** [comment]
Issues with the output should be reported on https://github.com/kangax/html-minifier/issues.
