### ISSUE TITLE
Issue with Vue.js / `@` properties

### ISSUE THREAD

**Issue by SteveEdson** [jonschlinkert/gulp-htmlmin#39]
[Vue.js](http://vuejs.org/) features event shorthand properties like so:

```
<!-- same as above -->
<input v-on:keyup.enter="submit">

<!-- also works for shorthand -->
<input @keyup.enter="submit">
```

This currently causes this gulp plugin to fail without any error output (making debugging this issue tricky and take forever).

Is it possible to allow exceptions / ignore invalid HTML / at least give an error etc.

Thanks.

**Comment by doowb** [comment]
To capture errors in a stream, you need to use the `.on('error', ...)` listener:

```js
gulp.task('min', function() {
  return gulp.src('path/to/files/*.html')
    .pipe(htmlmin())
    .on('error', console.error)
    .pipe(gulp.dest('dist'));
});
```

I added the html above to a file and I get a `Parse Error` from [html-minifier](https://github.com/kangax/html-minifier).

See their docs for available options and/or open an issue there if an option doesn't help with the vue.js syntax.

**Comment by SteveEdson** [comment]
Thanks for the help, opened an issue at https://github.com/kangax/html-minifier/issues/479

**Comment by SteveEdson** [comment]
Fixed with


```javascript
         ...
        .pipe(htmlmin({
            collapseWhitespace: true,
            customAttrSurround: [
                [/@/,/(?:)/]
            ]
        }).on('error', console.error))
       ...
```
