### ISSUE TITLE
There is whitespace between elements

### ISSUE THREAD

**Issue by yairEO** [jonschlinkert/gulp-htmlmin#4]
```
<a href='#'></a>
<a href='#'></a>
<a href='#'></a>
```

Gives:
`
<a href='#'></a> <a href='#'></a> <a href='#'></a>
`
please consider replacing all `> <` gaps with just `><`

**Comment by stanleyxu2005** [comment]
You cannot remove one space in this case `> </'. 
But you can reduce multiple spaces to one. `>      </` -> '> </'.

**Comment by yairEO** [comment]
doesn't destroy anything.. I use regex all the time to get rid of this pesky white-space between nodes. it's unwanted and cause layout issues. 

This is what I use:

    html.replace( new RegExp( "\>[\r\n ]+\<" , "g" ) , "><" );
