### ISSUE TITLE
File not written, output is printed to stdout

### ISSUE THREAD

**Issue by flawyte** [jonschlinkert/gulp-htmlmin#40]
Hi,

I'm using this plugin to minify a `vulcanize`d HTML file. Here's my `minify` task :

```javascript
gulp.task('minify', [ 'build' ], function() {
  return gulp
    .src('build/*.html')
    .pipe(minify({
      collapseInlineTagWhitespace: true,
      collapseWhitespace: true,
      keepClosingSlash: true,
      minifyCSS: true,
      minifyJS: true,
      removeComments: true,
      removeCommentsFromCDATA: true,
      removeRedundantAttributes: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true
    }))
    .pipe(gulp.dest('build2/'))
    ;
});
```

However when I run the task, no `build2/` directory is created, the result is printed to stdout. Another problem I have is that what is printed out is just the source HTML file, not minified. Why?

**Comment by jonschlinkert** [comment]
Closing since this doesn't seem related to this plugin. please ask stream- or gulp-related implementation questions on stackoverflow
