### ISSUE TITLE
A problem about htmlminifier, but I think it is related with this.

### ISSUE THREAD

**Issue by zyf0330** [jonschlinkert/gulp-htmlmin#41]
I found a bug of htmlminifier.It is that specific abnormal HTML tag tastes htmlminifier very long time to process, when it does regex match using its htmlparser, but it will still return null . 
What I care is that do you handle the null from ab abnormal html tag ? It is not good if a custom tag disappears from new file without an alert.

**Comment by zyf0330** [comment]
Another bug.
This html content 
`<pictureviewer v-ref:vm_pv :imgs="obj.pics_url" src_field="src" @pictureviewer.close ="close($index)"></pictureviewer><a v-ref:vm_pv :imgs=" objpicsurl_ " @pictureviewer.close ="close($index)"></a>`
this is gulp-htmlmin options 
`{
				removeComments: true,
				collapseWhitespace: true,
				minifyJS: {
					output:{
						quote_style: 3
					}
				},
				minifyCSS: true,
				ignoreCustomFragments: [/ ?@[\w\.]+ *= *['"].+['"]/]
			}`
The focus is if I enter at the end of first tag, the output is normal, but if I put two tags into one line, output is wrong.

**Comment by jonschlinkert** [comment]
Did you test this directly with `htmlminifier`?

**Comment by zyf0330** [comment]
@jonschlinkert  it is also one problem of `htmlminifier`. I am sorry.

**Comment by zyf0330** [comment]
I solved this problem. it is caused because I write an improper regex to match from start to line end.
Sorry.

**Comment by jonschlinkert** [comment]
no prob, glad you got it worked out, and thx for letting me know

**Comment by zyf0330** [comment]
@jonschlinkert html-minifier has fixed issue 'https://github.com/kangax/html-minifier/issues/507', not above problem.But also an important.
