### ISSUE TITLE
issue with php spaces

### ISSUE THREAD

**Issue by sameh0** [jonschlinkert/gulp-htmlmin#44]
i had this issue which i posted on htmlmin and they fixed it a release a while ago but it's not fixed here 
https://github.com/kangax/html-minifier/issues/545

**Comment by doowb** [comment]
Looks like they haven't published `1.3.0` yet. When they do, you can reinstall `gulp-htmlmin` and npm will pull down the latest because we're using `^1.0.0`.

**Comment by sameh0** [comment]
isn't possible to install directly from git ?

**Comment by doowb** [comment]
You can do that locally until `1.3.0` is published. I don't think it's a good idea for this library to depend on the git branch directly.
