### ISSUE TITLE
htmlmin reordering elements.

### ISSUE THREAD

**Issue by SmaugTheGreat** [jonschlinkert/gulp-htmlmin#47]
I'm trying to minify something like this: `<h1><span><div>test</div></span></h1>` but instead it results in this: `<h1><span></span><div>test</div></h1>` (note how the div is now outside the span). It does this not only for div but also for some other elements (for example h1 and h2), but it doesn't reorder other inline elements such as `<i>`.

These are the options that I'm using: 

    var htmlMinOptions = {
        collapseWhitespace: true,
        customAttrSurround: [ [/#/, /(?:)/], [/\*/, /(?:)/], [/\[?\(?/, /(?:)/] ],
        customAttrAssign: [ /\)?\]?=/ ],
        caseSensitive: true
    }

**Comment by YuliaTsareva** [comment]
+1
We also have such problem in our projects. It seems to be a breaking change in html-minifier.
https://github.com/kangax/html-minifier/issues/578

**Comment by poshest** [comment]
Can't wait for the upgrade to html-minifier 1.3.1 with the fix for this! :)

**Comment by shinnn** [comment]
All problems in the upstream project should be fixed in the upstream project, not in this plugin.

**Comment by SmaugTheGreat** [comment]
This is also what I thought. It would be awesome if under the report a bug section, there would be a link to the upstream project.

**Comment by shinnn** [comment]
@SmaugTheGreat Thanks for the advice. Is this OK? https://github.com/jonschlinkert/gulp-htmlmin/commit/a69cc25076c16dda636a3b7e7b850c96cbf8dc87

**Comment by SmaugTheGreat** [comment]
This is perfect, thanks!

**Comment by poshest** [comment]
@shinnn Thanks! The reason I made my comment is that html-minifier is now at 1.3.1, but gulp-htmlmin is only at 1.3.0.  I already installed gulp-htmlmin 1.3.0, and was expecting that for gulp-htmlmin to include the new changes to html-minifier, you would need to release a new version of gulp-htmlmin.  Are you saying that I just need to re-install 1.3.0 and I'll get the latest fixes to html-minifier?  That's not how I understood npm versioning to work.

**Comment by doowb** [comment]
@poshest when a package has a major version `1` or above (like `html-minifier`), then consuming packages like `gulp-htmlmin` can use a version range like `^1.0.0` that says "use the latest version with a major version of `1.x.x`. This means that if `html-minifier` bumps the minor... `1.2.0` to `1.3.0` or the patch ... `1.3.0` to `1.3.1`, we'll still get those changes.

Sometimes `npm` will cache versions locally and if the cached version matches a range, it won't do a remote request to see if there are newer versions. So, I'll usually delete my `node_modules` folder and do `npm cache clear && npm i` in projects to ensure that I get the latest dependencies.

Hope this clears things up.

**Comment by poshest** [comment]
@doowb Yes, it clears it up wonderfully.  Thank you very much for the explanation :)
