### ISSUE TITLE
Update deps to v.1.3.0 of html-minifier

### ISSUE THREAD

**Issue by igoradamenko** [jonschlinkert/gulp-htmlmin#48]
Hello!

Why are you not updating html-minifier version? I am getting errors in minified version with your plugin ('cause it depends on v.1.0.0). Please check this out: https://github.com/kangax/html-minifier/issues/581

I've tried update to v.1.3.0 and run tests. All of them are passing.

**Comment by jonschlinkert** [comment]
> Why are you not updating html-minifier version?

why didn't you do a pr instead of wasting time writing about it?

**Comment by igoradamenko** [comment]
Sorry about that. I just looking to PRs and found closed `Set the html-minifier dependency to 1.2.0 `. 

Here it is: #49

**Comment by jonschlinkert** [comment]
no worries, and sorry as well for my response. we've had a lot of issues about recent bugs in html-minifier
