### ISSUE TITLE
Error thrown on option tag

### ISSUE THREAD

**Issue by mrbinr** [jonschlinkert/gulp-htmlmin#51]
Hi,
When i use gulp-htmlmin on template containing twig element like <option {% if value=='1' %}selected="selected"{% endif %}>My Value</option> an error is thrown.
It's really strange, because if i remove it, and rerun gulp with other twig element in page everything works.

Any idea ?

Thanks for you help

Best Regards,

Pascall

**Comment by jonschlinkert** [comment]
please create errors related to parsing on https://github.com/kangax/html-minifier/issues
