### ISSUE TITLE
Feature: Option to remove comments.

### ISSUE THREAD

**Issue by ImranBug** [jonschlinkert/gulp-htmlmin#52]
It would be great if there was an option to remove html comments i.e:
`<!-- Header Start -->`

However keeping the browser based comments like the one for IE8 i.e:
     ``

**Comment by shinnn** [comment]
@ImranBug Please read at least the top of README before opening new issues.

**Comment by ImranBug** [comment]
Ops my bad! Going for (html-minifier)[https://github.com/kangax/html-minifier/issues?utf8=%E2%9C%93&q=comments]

**Comment by ImranBug** [comment]
Just in case any one else lands here: set `removeComments` to `true`.
