### ISSUE TITLE
child html tag moved from parent to sibling level

### ISSUE THREAD

**Issue by darkylmnx** [jonschlinkert/gulp-htmlmin#53]
hi,

i just had an issue but only on windows 10 not on osx or ubuntu. When the file is minified,i have some custom html tags (i'm using angular) and those tags are moved.

Example, this : 
`<div> <translate>HELLO</translate> </div> `
would turn to this : 
`<div>  </div> <translate>HELLO</translate>`

any idea why ?

**Comment by shinnn** [comment]
Read at least the top of README before opening new issues.

**Comment by jonschlinkert** [comment]
> Read at least the top of README before opening new issues.

Lol, now we can make that a [Saved Reply](https://github.com/blog/2135-saved-replies)!

**Comment by darkylmnx** [comment]
My bad sorry
