### ISSUE TITLE
Feature Request: Show summary of saved file space.

### ISSUE THREAD

**Issue by vangorra** [jonschlinkert/gulp-htmlmin#55]
After the minification is complete, gutil.log a summary of what was done.

Example output:
[12:08:44] Starting 'minifyHtml'...
[12:08:44] gulp-htmlmin: Minified 12 files (saved 18.2kb - 20%)
[12:08:44] Finished 'minifyHtml' after 297 ms

**Comment by jonschlinkert** [comment]
Interesting idea. Might be a good standalone gulp plugin that could be run on a set of files, before and after processing. e.g:

```html
gulp.src('foo/*.html')
  .pipe(size('before'))
  .pipe(minify())
  .pipe(size('after'))
```

**Comment by vangorra** [comment]
Good idea. Seem it already exists.
https://github.com/ben-eb/gulp-bytediff

**Comment by jonschlinkert** [comment]
great, thanks for posting back! closing since this isn't really an issue here
