### ISSUE TITLE
not minifying correctly 

### ISSUE THREAD

**Issue by harshadbankar** [jonschlinkert/gulp-htmlmin#58]
In my project i have custom div like 

`<div><page:login:new:user></page:login:new:user></div>`

And when I do minify, it is getting converted as 
`<div><page:login :new:user=""></page:login></div>` 

Any idea on how to solve this ?

**Comment by shinnn** [comment]
Have you ever read at least the top of README before opening this issue?

**Comment by harshadbankar** [comment]
Sorry my mistake. I will create issue there.
BDW if you know anything rather than correcting non useful comment, Solve above issue

**Comment by jonschlinkert** [comment]
> Solve above issue

That's the point, we can't solve minifying issues.
