### ISSUE TITLE
Cannot read property 'gulp' of undefined when installing

### ISSUE THREAD

**Issue by aenciso** [jonschlinkert/gulp-htmlmin#61]
When I run 

`npm i gulp-htmlmin --save-dev`

I get

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "gulp-htmlmin" "--save-dev"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6

npm ERR! Cannot read property 'gulp' of undefined
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Apache24\htdocs\laravel\npm-debug.log

Even after deleting node_modules I get the same error.

Any help would be highly appreciated

Thanks

[npm-debug.txt](https://github.com/jonschlinkert/gulp-htmlmin/files/305806/npm-debug.txt)

**Comment by shinnn** [comment]
Your npm-shrinkwrap.json is broken.
