### ISSUE TITLE
processConditionalComments bug

### ISSUE THREAD

**Issue by dudeonthehorse** [jonschlinkert/gulp-htmlmin#62]
Hello!

"processConditionalComments: true" works fine for 

`<!--[if (gte mso 9)|(IE)]><table width="100%" align="center"><tr><td width="250"><![endif]-->`

and for 

``

but in this construction

``

I'm loosing all code between conditional comments.

Catched this bug in my email development framework https://github.com/dudeonthehorse/kilogram

**Comment by shinnn** [comment]
Read at least the top of README before opening new issues.
