### ISSUE TITLE
Module fsevents not compatible

### ISSUE THREAD

**Issue by janbiasi** [jonschlinkert/gulp-htmlmin#64]
Just for your information ...

`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:`
`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12`

I'am using: 
* OS: **Windows 10**
* Node.js: **v4.2.2**
* NPM: **v3.8.9**

**Comment by shinnn** [comment]
Why do you think `fsevents` installation failure is related to this plugin?

**Comment by janbiasi** [comment]
Sorry mate, was on the wrong repository! :100:
