### ISSUE TITLE
gulp-htmlmin & thymeleaf

### ISSUE THREAD

**Issue by luiz04nl** [jonschlinkert/gulp-htmlmin#65]
okay? I would like to use the gulp-htmlmin to minify html in combination with thymeleaf and spring, but generates the following error:

org.xml.sax.SAXParseException: The type of link element "must be terminated by the matching end tag" </ link> ".

possibly some mistakes
I not found an option or other solution, any suggestions?

**Comment by jonschlinkert** [comment]
this probably belongs on the [html-minifier](https://github.com/kangax/html-minifier) issues
