### ISSUE TITLE
HTmlmin loops forever

### ISSUE THREAD

**Issue by antonvank** [jonschlinkert/gulp-htmlmin#66]
The following typo localize" in the title  in stead of localize created the loop
<pf-summary-block class="col-md-3 clickable"
								  title="{{'journals.new' | localize"}}"
								  value="journalEntries=(workCtrl.filtered.journals).length"
								  ng-click="workCtrl.openNewJournals({result: 'journals'})"></pf-summary-block>

**Comment by shinnn** [comment]
Read at least the top of [README](https://github.com/jonschlinkert/gulp-htmlmin/blob/ebdefba695c9cad0e40297eb3a4950074e44187e/README.md) before opening new issues.
