### ISSUE TITLE
Parse error on valid HTML with "<" character

### ISSUE THREAD

**Issue by RoxKilly** [jonschlinkert/gulp-htmlmin#67]
The plugin is enable to parse valid HTML documents if their text contains `<`. For example:
```
<div> < back </div>
```

My gulp task:
```
gulp.task('build-html',function(){
    return gulp.src(appDev+'test.html')
        .pipe(htmlmin({collapseWhitespace: true}))
        .pipe(gulp.dest(appProd));
});
```

Generates error:
```
Error: Parse Error: < back </div>
    at new HTMLParser (html-minifier\src\htmlparser.js:236:13)
```

`gulp-htmlmin 2.0.0`

**Comment by shinnn** [comment]
Please read at least the top of README before opening new issues.

**Comment by RoxKilly** [comment]
@shinnn My apologies

**Comment by olets** [comment]
@RoxKilly see also http://stackoverflow.com/questions/39421606/gulp-htmlmin-fails-on-valid-document-workaround-or-abandon-plugin
