### ISSUE TITLE
Consider dropping object-assign.

### ISSUE THREAD

**Issue by jdalton** [jonschlinkert/gulp-htmlmin#70]
Node 4 and up have `Object.assign`. With Node 0.10 being unsupported in a few days and Node 0.12 unsupported by December it may be a good time to consider using `Object.assign`.

**Comment by jonschlinkert** [comment]
Actually I'm fine keeping object-assign around for a while longer. I'd be more comfortable revisiting in Dec.

**Comment by XhmikosR** [comment]
This should have been made a long time ago since html-minifer v3.0.0 only supports node >= 4.

**Comment by jonschlinkert** [comment]
yeah we can do this if someone wants to do a pr
