### ISSUE TITLE
option to minify css in html

### ISSUE THREAD

**Issue by jay8t6** [jonschlinkert/gulp-htmlmin#71]
Can you add an option to minify the css written in html?

**Comment by jay8t6** [comment]
I just saw the minifyCSS option in html minifier documentation, it still doesnt minify for some reason...

**Comment by shinnn** [comment]
https://github.com/jonschlinkert/gulp-htmlmin/commit/a69cc25076c16dda636a3b7e7b850c96cbf8dc87#diff-8191924d78e7652d71643c49ac2716c8R5

> *Issues with the HTML parser and __output__ should be reported on the [html-minifier](https://github.com/kangax/html-minifier/issues) issue tracker.*
