### ISSUE TITLE
How to uglify inline scripts inside the html?

### ISSUE THREAD

**Issue by yairEO** [jonschlinkert/gulp-htmlmin#77]
I would like to have a complete minification strategy and not just the HTML, while the scripts stay unminified

**Comment by shinnn** [comment]
Learn what you really should do from [the comment](https://github.com/jonschlinkert/gulp-htmlmin/issues/4#issuecomment-35735232) in [the issue you've created](https://github.com/jonschlinkert/gulp-htmlmin/issues/4).
