### ISSUE TITLE
Mind if I add babel and update some syntax?

### ISSUE THREAD

**Issue by yowainwright** [jonschlinkert/gulp-htmlmin#79]
## Goals
-  try to make the repo show up as `js` rather than `html`
-  update some very minor things in the readme

Awesome repo! 🙌 —which is why I figured I might help (but don't want to bother).

If it's cool, I'll submit a pr.

**Comment by jonschlinkert** [comment]
Add babel? For what? What syntax are you referring to?

**Comment by yowainwright** [comment]
It would just be updating the repo to use es6 (not needed at all). 😊

![jonschlinkert_gulp-htmlmin__minify_html](https://cloud.githubusercontent.com/assets/1074042/22277832/80229e3a-e273-11e6-876a-7427775b0201.jpg)
Also, with [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), it could look pretty clean to render tests as mainly JavaScript so that the repo would show up as a JavaScript Repository (see above). 

As far as the readme:
-  date update
-  yarn install 

~Thanks

**Comment by jonschlinkert** [comment]
Thanks for the offer, but there is no pressing reason to change to es6. If we were refactoring already and there was something in es6 that provided an advantage for something we needed to accomplish then I'd be in favor of it.  I do appreciate it.
