### ISSUE TITLE
gulp watch loop

### ISSUE THREAD

**Issue by rzb** [jonschlinkert/gulp-htmlmin#81]
After implementing gulp-htmlmin, gulp watch goes into an endless loop for me.

I'm on Laravel (elixir sits on top of gulp). 

```javascript
elixir.extend('compress', function() {
    new elixir.Task('compress', function() {
        return gulp.src('./storage/framework/views/*')
            .pipe(htmlmin({
                collapseWhitespace          : true,
                collapseInlineTagWhitespace : true,
                removeAttributeQuotes       : true,
                removeComments              : true,
                minifyJS                    : true,
                minifyCSS                   : true,
            }))
            .pipe(gulp.dest('./storage/framework/views/'));
    })
    .watch('./storage/framework/views/*');
});
```

**Comment by shinnn** [comment]
1. Try some other HTML processor plugins inside `watch` task. If you can reproduce infinite loop even when you use other plugins, this is an issue with `elixir.Task#watch`.
2. If you cannot reproduce infinite loop with other plugins, pinpoint the HTML file that causes neverending process and open a new issue on https://github.com/kangax/html-minifier/issues with full content of the HTML file.

**Comment by doowb** [comment]
@rzb also it looks like your src and dest paths are the same. Since `gulp-htmlmin` changes the files, `watch` will trigger.
