### ISSUE TITLE
htmlmin auto remove Closed label, E.g /

### ISSUE THREAD

**Issue by andy-huaan** [jonschlinkert/gulp-htmlmin#83]
Automatically deleting the end tag results in an error  E.g / in thymeleaf project
**1.Before compression**
```
<!DOCTYPE html>
<html lang="zh" xmlns:th="http://www.thymeleaf.org/">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
    <input />
</body>
</html>
```
2.After compression
`<!DOCTYPE html><html lang="zh" xmlns:th="http://www.thymeleaf.org/"><meta name="viewport" content="width=device-width,initial-scale=1"><input>`
Since there is no end tag，thymeleaf can not run

**Comment by shinnn** [comment]
Please read at least the top of README before opening new issues.
