### ISSUE TITLE
Update html-minifier to 3.5.5

### ISSUE THREAD

**Issue by TimVevida** [jonschlinkert/gulp-htmlmin#87]
The dependency `html-minifier` is already at version 3.5.5, but this gulp plugin seems to lag behind. Update please?

**Comment by shinnn** [comment]
> this gulp plugin seems to lag behind. 

No. 

> Update please?

No.

Read https://nodesource.com/blog/semver-tilde-and-caret/.

**Comment by TimVevida** [comment]
You are right. I'm sorry for filing the issue.
