### ISSUE TITLE
minifyCSS options

### ISSUE THREAD

**Issue by tobsn** [jonschlinkert/gulp-htmlmin#88]
I can't seem to figure out how to pass along options:
```
		.pipe(htmlmin({
			collapseWhitespace: true,
			removeComments: true,
			ignoreCustomFragments: [/<\?php((.|\r|\n)+?)\?>/gi,/<\?=(.+?)\?>/gi],
			sortAttributes: false,
			minifyCSS: true,
			minifyJS: true
		}))
```

what doesn't work:
`minifyCSS: {level:0},`
`minifyCSS: {level:{0:{}}},`

Maybe someone can tell me because I couldn't find any solution that works...

Thanks!

**Comment by shinnn** [comment]
https://github.com/kangax/html-minifier/tree/v3.5.7#options-quick-reference

> `minifyCSS` Minify CSS in style elements and style attributes (uses [clean-css](https://github.com/jakubpawlowicz/clean-css))

Instead of here, use clean-css issue tracker for questions about CSS minification.

**Comment by tobsn** [comment]
This isn't about clean css minification it's about how to pass along options from the htmlmin object via the minifyCSS key:

`.pipe(htmlmin({`

**Comment by doowb** [comment]
@tobsn this library (`gulp-htmlmin`) passes the options directly into `html-minifier`. The link that @shinnn posted indicates that `html-minifier` passes the `minifyCSS` options directly to `clean-css`.

If an option isn't working, then either `html-minifier` isn't passing them directly to `clean-css` or `clean-css` isn't handling those options.

If your question is about general options for `html-minifier`, then you should ask there.

**Comment by tobsn** [comment]
@doowb not sure how this doesnt fit - I'm asking how to pass it along, because the docs say true/false/function/object but passing on an object doesn't work, hence why im asking here...?

**Comment by doowb** [comment]
Those docs are on a different repository. You should be asking [here](https://github.com/kangax/html-minifier/)
