### ISSUE TITLE
Provide a CHANGELOG

### ISSUE THREAD

**Issue by AlbertoFdzM** [jonschlinkert/gulp-htmlmin#91]
It just makes it easier for the users to know what changes have been made between versions:
http://keepachangelog.com/en/0.3.0/

**Comment by jonschlinkert** [comment]
Thanks! Looking forward to the PR!

**Comment by junminstorage** [comment]
I saw those PRs being merged since last release:

#78 use latest html-minifier version 
#89 Use native Object.assign 
#90 Replace deprecated gulp-util
