### ISSUE TITLE
 Discard uncommented code

### ISSUE THREAD

**Issue by yashghelani** [jonschlinkert/gulp-htmlmin#93]
I have some code that I want to use only for development purposes. Is there any way to discard that code while minifying the file for production? Kinda like wrapping that code in a unique format to let the parser know it’s meant to be discarded.

**Comment by jonschlinkert** [comment]
Please create an issue here: https://github.com/kangax/html-minifier/issues

**Comment by yashghelani** [comment]
Oops. My bad. Should have read the README before creating an issue. Thanks @jonschlinkert 😄
