### ISSUE TITLE
Does not work when when ran on dynamically created .html file

### ISSUE THREAD

**Issue by n1ghtie** [jonschlinkert/gulp-htmlmin#95]
Hi,

I have an issue with minifying a dynamically created html file with gulp. 
I have a bunch on .html files, and a gulp tasks that concatenates them into an index.html.

So as an example of what I am actually doing.
1) gulp tasks to concatenate files from app/ folder into index.html and copy to dist/
2) run htmlmin on dist/index.html

in gulp it looks like this:
```javascript
gulp.task('html', ['fileinclude'] ,function() {
  // var isCollapse = config.prod ? true : false;
  return gulp.src('dist/index.html')
    .pipe(htmlmin({collapseWhitespace: true}))
    .pipe(gulp.dest('dist'))
    .pipe(livereload());
})
```

```javascript
gulp.task('fileinclude', function() {
  gulp.src(['app/index.html'])
    .pipe(fileinclude({
      prefix: '@@',
      basepath: '@root'
    }))
    .pipe(gulp.dest('dist'));
});
```

gulp.task('build', ['fileinclude', 'html']);

So when i ran gulp command, html file is build from bundle of other html files and is copied to dist folder, but not minified. I've tried changing an outout dist folder to dist2, no luck as well.

**Comment by doowb** [comment]
You need to return the stream in the `fileinclude` task to tell the `html` task to wait until that one is finished.

```js
gulp.task('fileinclude', function() {
  return gulp.src(['app/index.html'])
    .pipe(fileinclude({
      prefix: '@@',
      basepath: '@root'
    }))
    .pipe(gulp.dest('dist'));
});
```
